POST https://localhost:8443/auth/loginPropietario HTTP/1.1
Content-Type: application/json

{
    "username": "garzy",
    "password": "1234"
}

POST https://localhost:8443/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "mike",
    "password": "1234"
}


GET https://localhost:8443/herramientas/propietariosName/garzy HTTP/1.1

GET https://localhost:8443/propietarios/isPropietario/garzy HTTP/1.1


GET https://localhost:8443/alquileres/usuario/lnunez HTTP/1.1




DELETE https://localhost:8443/herramientas/9 HTTP/1.1