# POST https://localhost:8443/auth/loginPropietario HTTP/1.1
# Content-Type: application/json

# {
#     "username": "garzy",
#     "password": "1234"
# }

GET https://localhost:8443/propietariosName/garzy HTTP/1.1