POST http://localhost:8080/demo/add
Content-Type: application/json

{
    "nombre": "Hernan",
    "apellidos": "Garcia",
    "email": "hernan@email.com",
    "latitud": 40.403,
    "longitud": -39.782,
    "iban": "ES2926"
}
